version: '3.4'
services:
  db:
    image: mysql:5.7
    container_name: mysql_sf_db_1
    volumes:
      - ${PWD}/db/mysql_datadir:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # change please
      MYSQL_USER: symfony # change please
      MYSQL_PASSWORD: symfony # change please
      MYSQL_DATABASE: symfony # change please
    networks:
      symfony_app_network:
        ipv4_address: 172.66.77.2
  symfony:
    image: php_nginx_supervisor:1.0
    container_name: app_sf_1
    entrypoint: ["/start.sh"]
    volumes:
      - ${PWD}/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/conf/nginx/app.conf:/etc/nginx/http.d/default.conf
      - ${PWD}/conf/php/conf.d/symfony.prod.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ${PWD}/conf/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${PWD}/app:/var/www/html
    networks:
      symfony_app_network:
        ipv4_address: 172.66.77.3
    restart: always
    environment:
      TZ: Europe/Moscow
      APP_USER_UID: $APP_USER_UID
networks:
  symfony_app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.77.0/24 # because our app will work in 172.66.77.1 - 172.66.77.254 inner netowrk